name: Doctrine
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    uses: szl-holdings/.github/.github/workflows/doctrine-check.yml@86b933bd2d9393cbbf79366a3a267430c72ea6b3 # main
